version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region eu-west-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd authorization
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/authapp .
      - docker tag service/authapp 408832051344.dkr.ecr.eu-west-2.amazonaws.com/pod11-auth-registry:authapp
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 408832051344.dkr.ecr.eu-west-2.amazonaws.com/pod11-auth-registry:authapp
    - printf '[{"name":"pod11-authapp-container","imageUri":"%s"}]' 408832051344.dkr.ecr.eu-west-2.amazonaws.com/pod11-auth-registry:authapp > taskdefinition.json
artifacts:
  files:
    - authorization/taskdefinition.json